######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-04 15:41:05
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/RectangleInnerDrivenGrowth1_2_3_4_5_7.mdxm', 'no', 'no', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '32', 'Mesh/System/Save', 'OvuleFEMGrowth')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-04 15:42:52
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/FemMembranes.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case6/FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-04 15:49:02
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/FemMembranes.mdxv')
Process.Mesh__System__Load('', 'no', 'no', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '32', 'Mesh/System/Save', 'OvuleFEMGrowth')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '32', 'Mesh/System/Save', 'OvuleFEMGrowth')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '49, 50, 60. 70', 'Mesh/System/Save', 'OvuleFEMGrowth')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__21_Visualize_Growth('KIso Strain', '', 'Growth Labels', 'Fem Growth')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__21_Visualize_Growth('KIso Strain', '', 'Growth Labels', 'Fem Growth')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '49, 50, 60. 70', 'Mesh/System/Save', 'OvuleFEMGrowth')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-04 17:00:43
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/RectangleInnerDrivenGrowth1_2_3_4_5_7.mdxm', 'no', 'no', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '60', 'Mesh/System/Save', 'OvuleFEMGrowth')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/OvuleFEMGrowth_case7-0060.mdxm', 'no', 'no', '0')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '10', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '50', '1e-6', 'Yes', '10e-9', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10 Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Tools__System__Load_View('')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/OvuleFEMGrowth_case7-0060.mdxm', 'no', 'no', '0')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-24 16:47:22
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/FemMembranes.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/RectangleInnerDrivenGrowth1_2_3_4_5_7.mdxm', 'no', 'no', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '70', 'Mesh/System/Save', 'OvuleFEMGrowth-Case7')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/OvuleFEMGrowth-Case7-0070.mdxm', 'no', 'no', '0')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__21_Visualize_Growth('KIso Strain', '', 'Growth Labels', 'Fem Growth')
Process.Model__CCF__22_Display_Anisotropy_Propagation_Failure('Linear Triangle', 'Triangle Element', 'E2')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/OvuleFEMGrowth-Case7-0070.mdxm', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2Dsimulations/FEM_2DSimulations/3linesEpidermis/1+2+3+4+5+7/FemMembranesComparison.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-25 01:14:37
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/FemMembranes.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2Dsimulations/FEM_2DSimulations/3linesEpidermis/1+2+3+4+5+6+7/FemMembranes.mdxv')
