######## New MorphoDynamX session v2.0 r2-689: 2020-06-16 14:31:09
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/FemMembranes.mdxv')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E2', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Poisson', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('110', '110', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '2200', '0', '0.', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('110', '550', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '2200', '0', '0.', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '2200', '0', '0.', '1')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '2200', '0', '0.', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('110', '550', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '0', '0', '0.', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('110', '550', '0.3', '1', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('110', '550', '0.3', '1', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '0', '0', '0.', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '2200', '0', '0.', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('110', '550', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '440', '0', '0.', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/RectangleInnerDrivenGrowth1_2_3_4_5_6_7.mdxm', 'no', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '11, 22, 24, 26, 32, 37, 48, 49', 'Mesh/System/Save', 'OvuleFEMGrowth_case1_stiffness10PercHigher')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/OvuleFEMGrowth_case1_stiffness10PercHigher-0049.mdxm', 'no', 'no', '0')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/OvuleFEMGrowth_case1_stiffness10PercHigher-0049.mdxm', 'no', 'no', '0')
Process.Model__CCF__06a_Material_Properties('110', '500', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('110', '500', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '400', '0', '0.', '1')
Process.Model__CCF__06a_Material_Properties('110', '500', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '440', '0', '0.', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E2', '', 'Material Labels', 'TransIso Material')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/RectangleInnerDrivenGrowth1_2_3_4_5_6_7_stiffness10PercentHigher.mdxm', 'no', '0')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-16 15:31:55
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/RectangleInnerDrivenGrowth1_2_3_4_5_6_7_stiffness10PercentHigherIso.mdxm', 'no', 'no', '0')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/FemMembranes.mdxv')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/RectangleInnerDrivenGrowth1_2_3_4_5_6_7_stiffness10PercentHigherIso.mdxm', 'no', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '11, 22, 24, 26, 32, 37, 48, 49', 'Mesh/System/Save', 'OvuleFEMGrowth_case1_stiffness10PercHigher')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/OvuleFEMGrowth_case1_stiffness10PercHigher-0049.mdxm', 'no', 'no', '0')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-16 15:44:54
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/RectangleInnerDrivenGrowth1_2_3_4_5_6_7_stiffness10PercentHigherIso.mdxm', 'no', 'no', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '11, 22, 24, 26, 32, 37, 46, 49', 'Mesh/System/Save', 'OvuleFEMGrowth_case1_stiffness10PercHigher')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/OvuleFEMGrowth_case1_stiffness10PercHigher-0046.mdxm', 'no', 'no', '0')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/OvuleFEMGrowth_case1_stiffness10PercHigher-0046.mdxm', 'no', '0')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-16 19:42:22
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/RectangleInnerDrivenGrowth1_2_3_4_5_6_7_stiffness10PercentHigher.mdxm', 'no', 'no', '0')
Process.Model__CCF__06a_Material_Properties('110', '550', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '440', '0', '0.3', '1')
Process.Model__CCF__20_Visualize_Material('Young E2', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/RectangleInnerDrivenGrowth1_2_3_4_5_6_7_stiffness10PercentHigher.mdxm', 'no', 'no', '0')
Process.Model__CCF__20_Visualize_Material('Poisson', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('110', '550', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '440', '0', '0.3', '1')
Process.Model__CCF__20_Visualize_Material('Poisson', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E2', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Anisotropy', '', 'Material Labels', 'TransIso Material')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/RectangleInnerDrivenGrowth1_2_3_4_5_6_7_stiffness10PercentHigher.mdxm', 'no', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '11, 22, 24, 26, 32, 37, 48, 46, 49', 'Mesh/System/Save', 'OvuleFEMGrowth_case1_stiffness10PercHigher')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-16 20:01:05
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/RectangleInnerDrivenGrowth1_2_3_4_5_6_7_stiffness10PercentHigher.mdxm', 'no', 'no', '0')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/FemMembranes.mdxv')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '11, 22, 24, 26, 32, 37, 48, 49', 'Mesh/System/Save', 'OvuleFEMGrowth_case1_stiffness10PercHigher')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/OvuleFEMGrowth_case1_stiffness10PercHigher-0049.mdxm', 'no', 'no', '0')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/OvuleFEMGrowth_case1_stiffness10PercHigher-0049.mdxm', 'no', '0')
