######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-04 11:17:48
Process.Mesh__System__Load('', 'No', 'No', '1')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-04 12:04:24
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Model__CCF__Fem_Diffusion_Growth__03_Set_Diffusion_Dirchlet('1', '0.2', 'GrowthMorphogen1', 'GrowthDirichlet1')
Process.Model__CCF__Fem_Diffusion_Growth__01_Diffusion_Derivatives('Linear Triangle', 'Morphogen Triangle Element Growth', 'GrowthMorphogen1', '1e-6', '1', 'Yes', 'No', 'No', 'No')
Process.Model__CCF__Fem_Diffusion_Anisotropy__05_Morphogen_Visualize('AnisotropyE2Morphogen', 'E2Morphogen Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/RectangleInnerDrivenGrowth1_2_3_4_5_6_7.mdxm', 'no', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case7/FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-04 17:20:11
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-04 17:26:19
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Model__CCF__Fem_Diffusion_Anisotropy__04_Create_Diffusion_Element('Linear Triangle', 'Morphogen Triangle Element')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-05 16:55:15
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-05 19:10:44
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-10 14:33:36
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Model__CCF__Fem_Diffusion_Growth__00_Diffusion_Solver('10', '0.01', '.0001', '10', '10', '10', 'Newton', 'Bi-conjugate Gradient Stabilized', '200', '1e-20', 'Yes', 'Model/CCF/Fem Diffusion Growth/05 Morphogen Visualize', '10e-12', 'Model/CCF/Fem Diffusion Growth/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Growth/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Growth__05_Morphogen_Visualize('GrowthMorphogen1', 'Growth1 Morph Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element Growth')
Process.Model__CCF__Fem_Diffusion_Growth__05_Morphogen_Visualize('GrowthMorphogen1', 'Growth1 Morph Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element Growth')
Process.Model__CCF__Fem_Diffusion_Growth__00_Diffusion_Solver('10', '0.01', '.0001', '10', '10', '10', 'Newton', 'Bi-conjugate Gradient Stabilized', '200', '1e-20', 'Yes', 'Model/CCF/Fem Diffusion Growth/05 Morphogen Visualize', '10e-12', 'Model/CCF/Fem Diffusion Growth/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Growth/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Growth__03_Set_Diffusion_Dirchlet('1', '0.2', 'GrowthMorphogen1', 'GrowthDirichlet1')
Process.Model__CCF__Fem_Diffusion_Growth__00_Diffusion_Solver('10', '0.01', '.0001', '10', '10', '10', 'Newton', 'Bi-conjugate Gradient Stabilized', '200', '1e-20', 'Yes', 'Model/CCF/Fem Diffusion Growth/05 Morphogen Visualize', '10e-12', 'Model/CCF/Fem Diffusion Growth/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Growth/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Growth__05_Morphogen_Visualize('GrowthMorphogen1', 'Growth1 Morph Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element Growth')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-10 16:17:48
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Model__CCF__Fem_Diffusion_Growth__03_Set_Diffusion_Dirchlet('1', '0.2', 'GrowthMorphogen1', 'GrowthDirichlet1')
Process.Model__CCF__Fem_Diffusion_Growth__03_Set_Diffusion_Dirchlet('1', '0.2', 'GrowthMorphogen1', 'GrowthDirichlet1')
Process.Model__CCF__Fem_Diffusion_Growth__00_Diffusion_Solver('10', '0.01', '.0001', '10', '10', '10', 'Newton', 'Bi-conjugate Gradient Stabilized', '200', '1e-20', 'Yes', 'Model/CCF/Fem Diffusion Growth/05 Morphogen Visualize', '10e-12', 'Model/CCF/Fem Diffusion Growth/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Growth/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Growth__05_Morphogen_Visualize('GrowthMorphogen1', 'Growth1 Morph Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element Growth')
Process.Model__CCF__Fem_Diffusion_Growth__00_Diffusion_Solver('10', '0.01', '.0001', '10', '10', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '200', '1e-20', 'Yes', 'Model/CCF/Fem Diffusion Growth/05 Morphogen Visualize', '10e-12', 'Model/CCF/Fem Diffusion Growth/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Growth/02 Dirichlet Derivatives')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-10 18:16:30
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Model__CCF__Fem_Diffusion_Growth__03_Set_Diffusion_Dirchlet('1', '0.2', 'GrowthMorphogen1', 'GrowthDirichlet1')
Process.Model__CCF__Fem_Diffusion_Growth__00_Diffusion_Solver('10', '0.01', '.0001', '10', '10', '10', 'Newton', 'Bi-conjugate Gradient Stabilized', '200', '1e-20', 'Yes', 'Model/CCF/Fem Diffusion Growth/05 Morphogen Visualize', '10e-12', 'Model/CCF/Fem Diffusion Growth/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Growth/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Growth__05_Morphogen_Visualize('GrowthMorphogen1', 'Growth1 Morph Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element Growth')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-11 15:12:12
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Model__CCF__Fem_Diffusion_Growth__04_Create_Diffusion_Element('Linear Triangle', 'Morphogen Triangle Element Growth')
Process.Model__CCF__Fem_Diffusion_Growth__03_Set_Diffusion_Dirchlet('1', '0.2', 'GrowthMorphogen1', 'GrowthDirichlet1')
Process.Model__CCF__Fem_Diffusion_Growth__03_Set_Diffusion_Dirchlet('1', '0', 'GrowthMorphogen1', 'GrowthDirichlet1')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/RectangleInnerDrivenGrowth1_2_3_4_5_6_7.mdxm', 'no', '0')
Process.Tools__System__Load_View('')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/RectangleSetForDiffusionEquilibrium.mdxm', 'no', 'no', '0')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-20 14:17:58
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-20 14:18:23
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '11, 22, 24, 26, 32, 37, 48, 49', 'Mesh/System/Save', 'OvuleFEMGrowth_case1')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__21_Visualize_Growth('KIso Strain', '', 'Growth Labels', 'Fem Growth')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__Fem_Diffusion_Anisotropy__03_Set_Diffusion_Dirchlet('1', '0.2', 'AnisotropyE2Morphogen', 'AnisotropyE2Dirichlet')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('1', '1', '.0001', '1', '1', '10', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '200', '1.e-40', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Anisotropy__05_Morphogen_Visualize('AnisotropyE2Morphogen', 'E2Morphogen Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element')
Process.Model__CCF__Fem_Diffusion_Anisotropy__05_Morphogen_Visualize('AnisotropyE2Morphogen', 'E2Morphogen Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__Fem_Diffusion_Anisotropy__05_Morphogen_Visualize('AnisotropyE2Morphogen', 'E2Morphogen Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('1', '1', '.0001', '1', '1', '10', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '200', '1.e-40', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('1', '1', '.0001', '1', '1', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '200', '1.e-40', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('10', '10', '.0001', '10', '1', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '200', '1.e-40', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Anisotropy__05_Morphogen_Visualize('AnisotropyE2Morphogen', 'E2Morphogen Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element')
######## New MorphoDynamX session v2.0 r2-674-ge6183014: 2020-02-20 17:25:43
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Model__CCF__Fem_Diffusion_Growth__00_Diffusion_Solver('10', '0.01', '.0001', '10', '10', '10', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '200', '1e-20', 'Yes', 'Model/CCF/Fem Diffusion Growth/05 Morphogen Visualize', '10e-12', 'Model/CCF/Fem Diffusion Growth/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Growth/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Growth__05_Morphogen_Visualize('GrowthMorphogen1', 'Growth1 Morph Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element Growth')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('1', '1', '.0001', '1', '1', '10', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '200', '1.e-40', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '11, 22, 24, 26, 32, 37, 48, 49', 'Mesh/System/Save', 'OvuleFEMGrowth_case1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__21_Visualize_Growth('KIso Strain', '', 'Growth Labels', 'Fem Growth')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__Fem_Diffusion_Anisotropy__04_Create_Diffusion_Element('Linear Triangle', 'Morphogen Triangle Element')
Process.Model__CCF__Fem_Diffusion_Anisotropy__03_Set_Diffusion_Dirchlet('1', '0.2', 'AnisotropyE2Morphogen', 'AnisotropyE2Dirichlet')
Process.Model__CCF__Fem_Diffusion_Anisotropy__03_Set_Diffusion_Dirchlet('1', '0', 'AnisotropyE2Morphogen', 'AnisotropyE2Dirichlet')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('1', '1', '.0001', '1', '1', '10', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '200', '1.e-40', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('1', '1', '.0001', '1', '1', '10', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '1000', '1.e-80', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('10', '10', '.0001', '10', '1', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '1000', '1.e-40', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('10', '10', '.0001', '10', '1', '10', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '1000', '1.e-80', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Anisotropy__03_Set_Diffusion_Dirchlet('0', '0', 'AnisotropyE2Morphogen', 'AnisotropyE2Dirichlet')
Process.Model__CCF__Fem_Diffusion_Anisotropy__02_Dirichlet_Derivatives('1e-6', 'Yes', 'No', 'No', 'No', 'AnisotropyE2Dirichlet', 'AnisotropyE2Morphogen')
Process.Model__CCF__Fem_Diffusion_Anisotropy__03_Set_Diffusion_Dirchlet('1', '0.2', 'AnisotropyE2Morphogen', 'AnisotropyE2Dirichlet')
Process.Model__CCF__Fem_Diffusion_Anisotropy__03_Set_Diffusion_Dirchlet('1', '0', 'AnisotropyE2Morphogen', 'AnisotropyE2Dirichlet')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('10', '10', '.0001', '10', '1', '10', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '1000', '1.e-80', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('10', '10', '.0001', '10', '1', '10', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '1000', '1.e-80', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Anisotropy__05_Morphogen_Visualize('AnisotropyE2Morphogen', 'E2Morphogen Signal', 'Morphogen Gradient', 'Linear Triangle', 'Morphogen Triangle Element')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__Fem_Diffusion_Anisotropy__04_Create_Diffusion_Element('Linear Triangle', 'Morphogen Triangle Element')
Process.Model__CCF__Fem_Diffusion_Anisotropy__03_Set_Diffusion_Dirchlet('1', '0.2', 'AnisotropyE2Morphogen', 'AnisotropyE2Dirichlet')
Process.Model__CCF__Fem_Diffusion_Anisotropy__03_Set_Diffusion_Dirchlet('1', '0', 'AnisotropyE2Morphogen', 'AnisotropyE2Dirichlet')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('1', '1', '.0001', '1', '1', '1', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '2000', '1.e-80', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Anisotropy__00_Diffusion_Solver('1', '1', '.0001', '1', '1', '1', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '100', '1.e-80', 'Yes', 'Model/CCF/Fem Diffusion Anisotropy/05 Morphogen Visualize', '1.e-10', 'Model/CCF/Fem Diffusion Anisotropy/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Anisotropy/02 Dirichlet Derivatives')
######## New MorphoDynamX session v2.0 r2-689: 2020-05-05 16:52:28
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case2/FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-15 12:47:42
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Model__CCF__Fem_Diffusion_Growth__03_Set_Diffusion_Dirchlet('1', '0.22', 'GrowthMorphogen1', 'GrowthDirichlet1')
Process.Model__CCF__Fem_Diffusion_Growth__00_Diffusion_Solver('10', '0.01', '.0001', '10', '10', '10', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '200', '1e-20', 'Yes', 'Model/CCF/Fem Diffusion Growth/05 Morphogen Visualize', '10e-12', 'Model/CCF/Fem Diffusion Growth/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Growth/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Growth__00_Diffusion_Solver('10', '0.01', '.0001', '10', '10', '10', 'Diffusion Newton', 'Bi-conjugate Gradient Stabilized', '200', '1e-20', 'Yes', 'Model/CCF/Fem Diffusion Growth/05 Morphogen Visualize', '10e-12', 'Model/CCF/Fem Diffusion Growth/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Growth/02 Dirichlet Derivatives')
Process.Model__CCF__Fem_Diffusion_Growth__00_Diffusion_Solver('10', '0.01', '.0001', '10', '10', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '200', '1e-20', 'Yes', 'Model/CCF/Fem Diffusion Growth/05 Morphogen Visualize', '10e-12', 'Model/CCF/Fem Diffusion Growth/01 Diffusion Derivatives', 'Model/CCF/Fem Diffusion Growth/02 Dirichlet Derivatives')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/RectangleInnerDrivenGrowth1_2_3_4_5_6_7.mdxm', 'no', '0')
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-16 16:52:03
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '11, 22, 24, 26, 32, 37, 46, 48, 49', 'Mesh/System/Save', 'OvuleFEMGrowth_case1')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-16 17:31:32
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/RectangleInnerDrivenGrowth1_2_3_4_5_6_7.mdxm', 'no', 'no', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '11, 22, 24, 26, 32, 37, 48, 49', 'Mesh/System/Save', 'OvuleFEMGrowth_case1')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/OvuleFEMGrowth_case1-0049.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/OvuleFEMGrowth_case1-0049.mdxm', 'no', 'no', '0')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '440', '0', '0.', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('110', '550', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '440', '0', '0.', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '11, 22, 24, 26, 32, 37, 48, 46 49', 'Mesh/System/Save', 'OvuleFEMGrowth_case1_stiffness10percHigher')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/RectangleInnerDrivenGrowth1_2_3_4_5_6_7.mdxm', 'no', 'no', '0')
Process.Model__CCF__06a_Material_Properties('100', '500', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('100', '500', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '400', '0', '0.', '1')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '', 'Mesh/System/Save', 'OvuleFEMGrowth_case1')
######## New MorphoDynamX session v2.0 r2-689: 2020-06-16 19:22:29
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/RectangleInnerDrivenGrowth1_2_3_4_5_6_7.mdxm', 'no', 'no', '0')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E2', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__21_Visualize_Growth('KIso Strain', '', 'Growth Labels', 'Fem Growth')
Process.Model__CCF__22_Display_Anisotropy_Propagation_Failure('Linear Triangle', 'Triangle Element', 'E2')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Poisson', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__02_FEM_Solver('1', '0.01', '.0001', '1', '1', '10', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '200', '1e-20', 'Yes', '10e-9', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10 Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/0d18GrowthSignal/FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/RectangleInnerDrivenGrowth1_2_3_4_5_6_7.mdxm', 'no', 'no', '0')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('100', '500', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06a_Material_Properties('100', '500', '0.3', '1', 'TransIso Material')
Process.Model__CCF__06b_Material_Properties_based_on_Morphogens_(for_faces)('TransIso Material', 'Growth1 Morph Signal', 'Negative', 'None', '400', '0', '0.', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Young E2', '', 'Material Labels', 'TransIso Material')
Process.Model__CCF__20_Visualize_Material('Poisson', '', 'Material Labels', 'TransIso Material')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/Stiffness10percHigher/FemMembranes.mdxv')
Process.Tools__System__Load_View('')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/OvuleFEMGrowth_case1-0024.mdxm', 'no', 'no', '0')
