######## New MorphoDynamX session v2.0 r2-689: 2020-06-15 12:54:39
Process.Tools__System__Save_View('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/FemMembranes.mdxv')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/14 Set Trichome Growth', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '11, 22, 24, 26, 32, 37, 48, 49', 'Mesh/System/Save', 'OvuleFEMGrowth_case1_0d22Growth')
Process.Mesh__System__Load('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/0d22GrowthSigna/OvuleFEMGrowth_case1_0d22Growth-0049.mdxm', 'no', 'no', '0')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '20', 'Linear Triangle', 'Triangle Element')
Process.Mesh__Attributes__Manage_Attributes('0')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material')
Process.Mesh__System__Save('/home/gabriella/IMAGO_project/FEM_2DOvuleGrowthModel/case1/robustnessAnalysis/0d22GrowthSigna/OvuleFEMGrowth_case1_0d22Growth-0049.mdxm', 'no', '0')
Process.Tools__System__Load_View('/home/gabriella/IMAGO_project/FEM_2Dsimulations/FEM_2DSimulations/3linesEpidermis/FemMembranes.mdxv')
